#import "./fragments/BaseMovie.gql"
#import "./fragments/FullMovie.gql"

query fetchNewMovies(
  $from: DateTime
  $cursor: String
  $limit: Int
) {
  allMovies(
    filter: {
      releaseDate_gte: $from
    }
    after: $cursor
    first: $limit
  ) {
    id
    ...BaseMovie
    ...FullMovie
    showtimes {
      id
      playingAt
    }
  }
}
